<?php
/**
 * Created by PhpStorm.
 * User: xiaoniu
 * Date: 16/3/29
 * Time: 下午5:41
 */
return [
    'mysql.default_write' => [
        'book_lottery',
        'book_lottery_edit_log',
        'book_lottery_prize',
        'book_lottery_user_join',
        'book_lottery_user_take',
        'buyer_notice',
        'entity_certification',
        'goods_collection_configure',
        'goods_collection_data',
        'goods_pf',
        'labels',
        'labels_business_relation',
        'labels_goods_relation',
        'labels_mapping',
        'market',
        'market_category',
        'market_category_relation',
        'market_category_tag',
        'market_edit_log',
        'market_goods',
        'market_offline',
        'market_range',
        'market_shop',
        'market_shop_blacklist',
        'market_tag',
        'market_tag_shop_relation',
        'member_apply',
        'member_area',
        'member_invite',
        'member_log',
        'notice_category',
        'qualification_certification',
        'rule_team_relation',
        'scratch_card',
        'scratch_card_edit_log',
        'scratch_card_prize',
        'scratch_card_user_join',
        'scratch_card_user_take',
        'shop_common_notice',
        'shop_notice',
        'tag_goods_relation',
        'task_wxhb',
        'team_advertisement',
        'team_pf',
        'team_score',
        'team_score_record',
        'ump_guide_marketing',
        'ump_member_discount_join_log',
        'ump_time_limited_discount',
        'ump_time_limited_discount_goods_join',
        'ump_time_limited_discount_join_log',
        'user_follow',
        'user_goods_record',
        'user_select',
        'user_shop_record',
    ]
];