<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)-v1.0.1
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR YOUZAN, ANY PROBLEM PLS CONTACT lanhu(zhangyuanhao@qima-inc.com)
 * qingjiao(qingjiao@qima-inc.com) & xiao'er(shiyu@qima-inc.com)
 * @generated
 */

namespace Com\Yourcompany\Demo\Entity;

use Kdt\Iron\Nova\Foundation\Protocol\TStruct;
use Thrift\Type\TType;


class BaseStruct extends TStruct {
  /**
   * @var bool
   */
  public $propBool = null;
  /**
   * @var int
   */
  public $propByte = null;
  /**
   * @var int
   */
  public $propI16 = null;
  /**
   * @var int
   */
  public $propI32 = null;
  /**
   * @var int
   */
  public $propI64 = null;
  /**
   * @var double
   */
  public $propDouble = null;
  /**
   * @var string
   */
  public $propString = null;
  /**
   * @var int
   */
  public $errorLevel = null;

  protected $structSpec = [
    1 => [
      'var' => 'propBool',
      'type' => TType::BOOL,
      ],
    2 => [
      'var' => 'propByte',
      'type' => TType::BYTE,
      ],
    3 => [
      'var' => 'propI16',
      'type' => TType::I16,
      ],
    4 => [
      'var' => 'propI32',
      'type' => TType::I32,
      ],
    5 => [
      'var' => 'propI64',
      'type' => TType::I64,
      ],
    6 => [
      'var' => 'propDouble',
      'type' => TType::DOUBLE,
      ],
    7 => [
      'var' => 'propString',
      'type' => TType::STRING,
      ],
    8 => [
      'var' => 'errorLevel',
      'type' => TType::I32,
      ],
    ];

}

